name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: luffy-loop
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#E9B39A&color_dots=#18232D,#6E2D16,#8F3D18,#B95422,#D66A32
            dist/github-contribution-grid-snake-dark.svg?color_snake=#E9B39A&color_dots=#18232D,#6E2D16,#8F3D18,#B95422,#D66A32

      - name: Publish Snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
